import { useEffect, useState } from "react";
import { ArrowRight, Bot, Menu, Plus, Wrench, X, Download, Compass } from "lucide-react";
import { ViaMark } from "@/components/flow/logo";
import { BotAvatar } from "@/components/flow/bot-avatar";
import { Studio } from "@/components/flow/studio";
import { useFlowStore } from "@/lib/flow/store";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

type BotProject = { id: string; name: string; updatedAt: number };
const BOTS_KEY = "via-bots-v1";
const BOT_SNAPSHOT_PREFIX = "via-bot-snapshot-v1:";
function readBots(): BotProject[] { try { const raw=localStorage.getItem(BOTS_KEY); return raw ? JSON.parse(raw) as BotProject[] : []; } catch { return []; } }
function saveBots(bots: BotProject[]) { localStorage.setItem(BOTS_KEY, JSON.stringify(bots)); }

function InstallButton(){
 const [event,setEvent]=useState<any>(null);
 useEffect(()=>{const h=(e:any)=>{e.preventDefault();setEvent(e)};window.addEventListener("beforeinstallprompt",h);return()=>window.removeEventListener("beforeinstallprompt",h)},[]);
 if(!event)return null;
 return <Button variant="ghost" onClick={async()=>{await event.prompt();setEvent(null)}}><Download className="size-4"/>Instalar Vía</Button>;
}

export function Home(){
 const [screen,setScreen]=useState<"home"|"workshop"|"bots"|"editor">("home");
 const [bots,setBots]=useState<BotProject[]>([]); const [creating,setCreating]=useState(false); const [activeBotId,setActiveBotId]=useState<string|null>(null); const [menuOpen,setMenuOpen]=useState(false);
 const [botSearch,setBotSearch]=useState("");
 const hydrate=useFlowStore(s=>s.hydrate), setName=useFlowStore(s=>s.setName), resetBlank=useFlowStore(s=>s.resetBlank), loadSnapshot=useFlowStore(s=>s.loadSnapshot);
 useEffect(()=>setBots(readBots()),[]);
 useEffect(()=>{if(!activeBotId)return; return useFlowStore.subscribe(state=>{localStorage.setItem(`${BOT_SNAPSHOT_PREFIX}${activeBotId}`,JSON.stringify({name:state.name,identity:state.identity,nodes:state.nodes,edges:state.edges,trainingEnabled:state.trainingEnabled,trainingExamples:state.trainingExamples,learningCandidates:state.learningCandidates}))})},[activeBotId]);
 const openNewBot=()=>{setCreating(true);setMenuOpen(false)};
 const createBot=()=>{const name="Borrador sin nombre", bot={id:crypto.randomUUID(),name,updatedAt:Date.now()},next=[bot,...bots];saveBots(next);setBots(next);hydrate();resetBlank();setName(name);setActiveBotId(bot.id);localStorage.setItem(`${BOT_SNAPSHOT_PREFIX}${bot.id}`,JSON.stringify({name,identity:useFlowStore.getState().identity,nodes:useFlowStore.getState().nodes,edges:useFlowStore.getState().edges,trainingEnabled:useFlowStore.getState().trainingEnabled,trainingExamples:useFlowStore.getState().trainingExamples,learningCandidates:[]}));setCreating(false);setScreen("editor")};
 const finishBot=(name:string)=>{if(!activeBotId)return;const cleanName=name.trim()||"Mi bot";const next=bots.map(bot=>bot.id===activeBotId?{...bot,name:cleanName,updatedAt:Date.now()}:bot);saveBots(next);setBots(next);setName(cleanName);localStorage.setItem(`${BOT_SNAPSHOT_PREFIX}${activeBotId}`,JSON.stringify({name:cleanName,identity:useFlowStore.getState().identity,nodes:useFlowStore.getState().nodes,edges:useFlowStore.getState().edges,trainingEnabled:useFlowStore.getState().trainingEnabled,trainingExamples:useFlowStore.getState().trainingExamples,learningCandidates:useFlowStore.getState().learningCandidates}));setScreen("workshop")};
 const openBot=(bot:BotProject)=>{hydrate();setActiveBotId(bot.id);try{const raw=localStorage.getItem(`${BOT_SNAPSHOT_PREFIX}${bot.id}`);if(raw)loadSnapshot(JSON.parse(raw));else setName(bot.name)}catch{setName(bot.name)}setScreen("editor")};
 const filtered=bots.filter(b=>b.name.toLowerCase().includes(botSearch.toLowerCase()));
 if(screen==="editor")return <Studio onBackToWorkshop={()=>setScreen("workshop")} onFinishBot={finishBot}/>;
 const Header=({title}:{title?:string})=><header className="sticky top-0 z-30 flex h-16 items-center border-b border-line bg-surface/95 px-4 backdrop-blur sm:px-6"><button type="button" onClick={()=>setScreen("home")} className="flex items-center gap-2 rounded-xl px-2 py-1.5 font-medium hover:bg-raised"><ViaMark className="size-8"/><span className="font-display text-xl">Vía</span></button>{title&&<><div className="ml-3 h-6 w-px bg-line"/><span className="ml-3 text-sm font-medium text-muted">{title}</span></>}<div className="ml-auto flex items-center gap-1"><InstallButton/><Button variant="ghost" size="icon" onClick={()=>setMenuOpen(true)} aria-label="Abrir menú"><Menu className="size-5"/></Button></div></header>;
 const MenuSheet=menuOpen?<div className="fixed inset-0 z-50 bg-ink/30" onClick={()=>setMenuOpen(false)}><div className="absolute right-0 top-0 h-full w-[min(88vw,360px)] bg-surface p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><div className="flex items-center gap-2"><ViaMark className="size-8"/><span className="font-display text-xl">Menú de Vía</span></div><Button variant="ghost" size="icon" onClick={()=>setMenuOpen(false)}><X className="size-5"/></Button></div><div className="mt-6 grid gap-2"><button className="flex items-center gap-3 rounded-2xl p-4 text-left hover:bg-raised" onClick={()=>{setScreen("workshop");setMenuOpen(false)}}><Wrench className="size-5 text-forest"/><span><b className="block">Taller</b><small className="text-muted">Crear y editar bots</small></span></button><button className="flex items-center gap-3 rounded-2xl p-4 text-left hover:bg-raised" onClick={()=>{setScreen("bots");setMenuOpen(false)}}><Compass className="size-5 text-forest"/><span><b className="block">Visitar bots</b><small className="text-muted">Explora los bots que has creado</small></span></button></div></div></div>:null;
 if(screen==="bots")return <div className="min-h-dvh bg-bg text-ink"><Header title="Visitar bots"/>{MenuSheet}<main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-sm font-medium text-forest">VISITAR BOTS</p><h1 className="font-display text-4xl tracking-tight sm:text-5xl">Tu colección</h1><p className="mt-3 max-w-2xl text-muted">Cada bot tiene su propio personaje, flujo, entrenamiento y memoria local.</p></div><div className="flex gap-2"><Input value={botSearch} onChange={e=>setBotSearch(e.target.value)} placeholder="Buscar bot..." className="w-48"/><Button onClick={openNewBot}><Plus className="size-4"/>Crear bot</Button></div></div>{filtered.length===0?<div className="mt-8 rounded-3xl border border-dashed border-line bg-surface p-10 text-center"><BotAvatar id="empty" size="lg" className="mx-auto"/><h2 className="mt-5 font-display text-2xl">Todavía no hay bots</h2><p className="mt-2 text-sm text-muted">Crea uno en el Taller y aparecerá aquí.</p><Button className="mt-5" onClick={openNewBot}>Crear mi primer bot</Button></div>:<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(bot=><button key={bot.id} type="button" onClick={()=>openBot(bot)} className="group rounded-3xl border border-line bg-surface p-5 text-left transition hover:-translate-y-1 hover:shadow-[var(--shadow-border-hover)]"><div className="flex items-center justify-between"><BotAvatar id={bot.id} size="lg"/><ArrowRight className="size-5 text-subtle transition group-hover:translate-x-1 group-hover:text-forest"/></div><h2 className="mt-5 font-display text-2xl">{bot.name}</h2><p className="mt-1 text-sm text-muted">Bot de Vía · {new Date(bot.updatedAt).toLocaleDateString("es-CO")}</p></button>)}</div>}</main>{creating&&<CreateModal onCancel={()=>setCreating(false)} onCreate={createBot}/>}</div>;
 if(screen==="workshop")return <div className="min-h-dvh bg-bg text-ink"><Header title="Taller"/>{MenuSheet}<main className="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-12"><div className="mb-8"><p className="mb-2 text-sm font-medium text-forest">TALLER</p><h1 className="font-display text-4xl tracking-tight sm:text-5xl">Crea tus bots</h1><p className="mt-3 max-w-2xl text-muted">Diseña conversaciones, añade botones, listas e inteligencia artificial, entrena tu bot y revisa el flujo antes de terminarlo.</p></div><div className="grid gap-4 sm:grid-cols-2"><button type="button" onClick={openNewBot} className="group flex min-h-48 flex-col justify-between rounded-3xl border border-line bg-surface p-6 text-left transition hover:-translate-y-1 hover:shadow-[var(--shadow-border-hover)]"><span className="flex size-12 items-center justify-center rounded-2xl bg-forest text-surface"><Plus className="size-6"/></span><span><span className="block font-display text-2xl">Crear nuevo bot</span><span className="mt-1 block text-sm text-muted">Empieza en blanco y ponle nombre al terminar.</span></span></button><button type="button" onClick={()=>setScreen("bots")} className="group flex min-h-48 flex-col justify-between rounded-3xl border border-line bg-surface p-6 text-left transition hover:-translate-y-1 hover:shadow-[var(--shadow-border-hover)]"><span className="flex size-12 items-center justify-center rounded-2xl bg-raised text-forest"><Compass className="size-6"/></span><span><span className="block font-display text-2xl">Visitar bots</span><span className="mt-1 block text-sm text-muted">Abre tus bots y continúa trabajando en ellos.</span></span></button></div></main>{creating&&<CreateModal onCancel={()=>setCreating(false)} onCreate={createBot}/>}</div>;
 return <div className="min-h-dvh bg-bg text-ink"><main className="mx-auto flex min-h-dvh max-w-6xl flex-col px-5 py-8 sm:px-8 sm:py-12"><header className="flex items-center gap-3"><ViaMark className="size-10"/><span className="font-display text-2xl tracking-tight">Vía</span><div className="ml-auto flex gap-1"><InstallButton/><Button variant="ghost" size="icon" onClick={()=>setMenuOpen(true)}><Menu className="size-5"/></Button></div></header>{MenuSheet}<section className="flex flex-1 flex-col justify-center py-12"><p className="text-sm font-medium uppercase tracking-[0.2em] text-forest">Vía · Beta 0.1.0</p><h1 className="mt-3 max-w-3xl font-display text-5xl leading-[0.98] tracking-tight sm:text-7xl">Tu espacio para crear bots.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-muted sm:text-lg">Construye conversaciones visualmente, entrena respuestas, prueba el comportamiento y guarda todos tus bots en un solo lugar.</p><div className="mt-10 grid max-w-2xl gap-3 sm:grid-cols-2"><button type="button" onClick={()=>setScreen("workshop")} className="flex items-center gap-4 rounded-3xl border border-line bg-surface p-5 text-left shadow-[var(--shadow-border)] transition hover:-translate-y-0.5"><span className="flex size-12 items-center justify-center rounded-2xl bg-forest text-surface"><Wrench className="size-5"/></span><span className="flex-1"><b className="block font-display text-xl">Taller</b><small className="text-muted">Crea y edita bots.</small></span><ArrowRight className="size-5 text-muted"/></button><button type="button" onClick={()=>setScreen("bots")} className="flex items-center gap-4 rounded-3xl border border-line bg-surface p-5 text-left shadow-[var(--shadow-border)] transition hover:-translate-y-0.5"><span className="flex size-12 items-center justify-center rounded-2xl bg-raised text-forest"><Compass className="size-5"/></span><span className="flex-1"><b className="block font-display text-xl">Visitar bots</b><small className="text-muted">Explora tus bots.</small></span><ArrowRight className="size-5 text-muted"/></button></div></section><footer className="pt-8 text-xs text-subtle">Vía · Constructor y entrenador de bots · Beta 0.1.0</footer></main></div>;
}

function CreateModal({onCancel,onCreate}:{onCancel:()=>void;onCreate:()=>void}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/30 p-4"><div className="w-full max-w-md rounded-3xl bg-surface p-6 shadow-2xl"><BotAvatar id="new-bot" size="md"/><h2 className="mt-4 font-display text-2xl">Crea tu bot</h2><p className="mt-1 text-sm leading-6 text-muted">Entra al taller, construye el flujo, entrena su IA y al terminar podrás ponerle el nombre definitivo.</p><div className="mt-5 rounded-2xl bg-raised p-4 text-xs leading-5 text-muted"><b className="text-ink">Incluye:</b> editor visual, entrenamiento, aprendizaje supervisado, simulador, revisión y guardado local.</div><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={onCancel}>Cancelar</Button><Button onClick={onCreate}>Entrar al taller</Button></div></div></div>}
